services:
  postgres:
    build: .
    image: pgvector-postgis:pg17
    container_name: postgres_pgvector
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=FP_PRUEBAS"
      - "-c"
      - "cron.timezone=America/Mazatlan"
      - "-c"
      - "TimeZone=America/Mazatlan"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-FP_PRUEBAS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-FP_PRUEBAS}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
